### ISSUE TITLE
Response time exaggerated 

### ISSUE THREAD

**Issue by mxsmns** [mxsmns/traceroute#1]
The response time for each hop in the traceroute seems to be much larger than is expected.

**Comment by mxsmns** [comment]
I think this has to do with the loop that goes through all of the packets up to TTL limit. Since packets go in the order that they were sent (not the order that they are received), some packets may have to wait to be received. Maybe adding an initial loop to loop for a certain amount of time/certain number of iterations to receive packets in fastest order would provide the correct output.

**Comment by igrande0** [comment]
hi

**Comment by mxsmns** [comment]
Excuse me this is a private chat room.
