### ISSUE TITLE
Vector subscript errors

### ISSUE THREAD

**Issue by mxsmns** [mxsmns/traceroute#2]
On hosts with long ping times, there is a vector subscript out of range error. It seems like maybe it is trying to process before the index is created. If this is fixed, the delay after sending can probably be removed.

**Comment by igrande0** [comment]
hello mxmns

**Comment by mxsmns** [comment]
hello igan

**Comment by mxsmns** [comment]
Looks like the RTO for the receive function was too low so it was timing out before the packet got back. Raising RTO solves the issue, but leads to same inconsistent timing as #1.
